version: '3.5'

services:
  mysql:
    image: mysql:5
    container_name: mysql
    networks: [main]
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqldata:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3
    container_name: amqp
    networks: [main]

  server:
    build: .
    container_name: server
    networks: [main]
    command: ["sh", "/wait-and-run.sh", "/server-entrypoint.sh"]
    ports:
      - 8000:8000
    env_file:
      - ./docker-compose/.env

  command_consumer:
    build: .
    container_name: command_consumer
    networks: [main]
    command: ["sh", "/wait-and-run.sh", "/command-consumer-entrypoint.sh"]
    env_file:
      - ./docker-compose/.env

volumes:
  mysqldata:
    driver: local

networks:
  main: